### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by HeroofHell** [drenther/bdnd_example#1]
When I run "npm run build" I always get this error: npm ERR! Invalid name: "Line up the heroes"

Full error log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose stack Error: Invalid name: "Line up the heroes"
4 verbose stack     at ensureValidName (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:336:15)
4 verbose stack     at Object.fixNameField (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:215:5)
4 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (<anonymous>)
4 verbose stack     at normalize (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:411:5)
4 verbose stack     at then (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd C:\xampp2\htdocs\todonew
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v10.16.0
9 verbose npm  v6.9.0
10 error Invalid name: "Line up the heroes"
11 verbose exit [ 1, true ]

**Comment by drenther** [comment]
You can change the name in the package.json to something that doesn't have spaces like "line_up_the_heroes". It should work then.

**Comment by drenther** [comment]
I am closing this.
